services:
  iris:
    image: containers.intersystems.com/intersystems/irishealth-community-arm64:latest-preview
    container_name: iris-health-arm64
    restart: unless-stopped
    
    ports:
      - "52773:52773"  # IRIS Web Server Port
      - "1972:1972"  # IRIS Super Server Port

    volumes:
      - iris-durable:/durable

volumes:
  iris-durable:
